### PR TITLE
Improve the README, compress the icon

### PR DESCRIPTION
**Pull request by RaptaG**
Thanks, for actually updating this mod. Could you enable the Issues section as well?
Also, I'd appreciate some GIFs, so that I can add them here.

### CODE REVIEW

**Comment by RaptaG** [comment]
Tool used for the compression: https://imagecompressor.com
Colors are set to `6`

**Comment by TopchetoEU** [comment]
Alright, I'm going to check it out now. Sorry for not responding earlier

**Comment by TopchetoEU** [comment]
Thanks for making a pull request :)

**Comment by RaptaG** [comment]
You're welcome!

**Pull request merged**
